language: r
cache: packages

install_r:
  - devtools

r_github_packages:
  - csgillespie/efficient

script:
  - R CMD INSTALL ../efficientR/
  - make html

  
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change
    
env:
  global:
    secure: U4QPoKPSF6f71b7u31PI3hgn1mmbKrzWjTVBDE9mbegjCeyOI37SXq4OlJbxXThTE9g6zYTa9ZutZgh9QIjZ1Lj38/K/kjXBcOhWY7BetwcRI4cstvZuv3uFhxKJwVLlsldZfLwglsMXopY310p/zxJWnxs5SHbvQ89LkFVUudWihopFLtnTfTCBCp/SbCrZTiblrnc6g0VPhyE1KeT9YNT857eEw6g5hnosFNbSSnTGLi+7rliEOHSpiUXg9v6g3XBKC8zfxHDBFdpDnFaZctpPk3kq5qQCTJGmIXZ+4P8C2YD0il2FXqP8Bxgif0LK+hjJAL0eowJaQ/ZJXSwMBDVBpkBnDBeeCphxA8Xnlq1j9Wy2iIFnIU5qeuR1lATLh1DRMR2+/ikEYMl456NHq1Z5QuNB8N1lwHN5Ui4GRHQE5ecxr1xnZt1TiI93+A+EhAV/0VfZnhcNZF5EJROoGfL4j08ZKm/F3rxN1OqvwV5u8sS859mS3osmxyN30q/mTTKiT7G6XWMHvZf3y6QCCX/Didll4k2ZlzNeDkjq9FThUNypJztcl6v2AqZQBjzyNDg1TNc7L1odr86iLMYohBDv+rNq8pl+fv6uFQYz0DwrNHn6/X6ZurNSJr13V/QUR/Csh0Vyn73seN9dAa77K/ajHTy9yNksddjvjjw4ID4=
